# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20160707_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='questioncount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='exam',
            name='total',
            field=models.IntegerField(default=10),
        ),
    ]
