# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-09 08:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20160707_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='total',
        ),
    ]
